#define DEBUGUI_GroundChunkOutline 0 // b32
#define DEBUGUI_GroundCheckChekerboards 0 // b32
#define DEBUGUI_RecomputeGroundChunksOnEXEChange 0 // b32
#define DEBUGUI_ParticleTest 0 // b32
#define DEBUGUI_ParitcleGrid 0 // b32
#define DEBUGUI_TestWeirdDrawBufferSize 0 // b32
#define DEBUGUI_ShowLightingSamples 0 // b32
#define DEBUGUI_UsedDebugCamera 1 // b32
#define DEBUGUI_UseRoomBasedCamera 0 // b32
#define DEBUGUI_UseSpacesOutline 0 // b32
#define DEBUGUI_FamiliarFollowsHero 0 // b32
